# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HT_USER',
        ),
    ]
