# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_ht_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('balance', models.FloatField(default=0)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HT_USER',
        ),
    ]
