# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20171013_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(db_index=True, max_length=254, primary_key=True, serialize=False),
        ),
    ]
