# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20170921_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersuggestions',
            name='id',
        ),
        migrations.AddField(
            model_name='usersuggestions',
            name='_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
