# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20170921_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestions',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
