# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20170921_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
