# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0007_delete_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.TextField(max_length=254)),
                ('content', models.TextField()),
                ('record_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
